version: '3.8'

services:
  hugo:
    image: klakegg/hugo:latest-ext
    command: server --bind 0.0.0.0 --disableFastRender --noHTTPCache
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    environment:
      - HUGO_WATCH=true
      - HUGO_BIND=0.0.0.0
      - HUGO_PORT=1313
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge 